spring:
  datasource:
    url: jdbc:mysql://localhost:3306/out_of_the_nest?useSSL=false&serverTimezone=UTC
    username: root
    password:
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.conestoga.outofthenest.model

server:
  port: 8080

logging:
  level:
    org.mybatis.spring: DEBUG
    org.apache.ibatis: DEBUG