spring:
  datasource:
    url: jdbc:mysql://bjndikbt4thmi9kvkf0l-mysql.services.clever-cloud.com:3306/bjndikbt4thmi9kvkf0l?useSSL=false&allowPublicKeyRetrieval=true
    username: uyzlilojd9rea7rm
    password: I1KiDjHDkwrAatnOzg24
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.conestoga.outofthenest.model


server:
  port: 8080

logging:
  level:
    org.mybatis.spring: INFO
    org.apache.ibatis: INFO